import Head from "next/head";
import { AiFillGithub, AiFillLinkedin, AiFillYoutube } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import frontend from "../public/frontend.png";
import backend from "../public/backend.png";
import hoobank from "../public/hoobank.png";
import jira from '../public/jira.png'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Muhammad Junaid | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Muhammad Junaid</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Muhammad Junaid
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Engineer | MERN Stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Experienced Software Engineer with 6+ months of MERN stack
              development experience. Skilled in designing, developing, and
              maintaining software applications that meet client needs.
              Collaborative team player committed to staying up-to-date with
              emerging technologies and industry trends.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/muhammad-junaid-26b930149/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Muhammad-Junaid-24/">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              Technologies I Have Used
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Here are all the awesome technologies I&apos;ve worked with
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={frontend} width={100} height={100} />
              <h3 className="text-lg text-teal-600 font-semibold pt-8 pb-2">
                Frontend Technologies
              </h3>
              <p className="text-gray-800 py-1">React + Redux</p>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">NextJS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={backend} width={100} height={100} />
              <h3 className="text-lg mt-5 py-2 text-teal-600 font-semibold">
                Backend Technologies & Databases
              </h3>
              <p className="text-gray-800 py-1">NodeJS</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">PostgreSQL</p>
              <p className="text-gray-800 py-1">MongoDB</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={jira} width={150} height={100} className="object-contain"/>
              <h3 className="text-lg font-semibold pt-8 pb-2 text-teal-600">
                Miscellaneous
              </h3>
              <p className="text-gray-800 py-1">JIRA</p>
              <p className="text-gray-800 py-1">Git & Github</p>
              <p className="text-gray-800 py-1">
                Stripe For Digital Payment Processing
              </p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Take a look at some of the cool projects I&apos;ve made
            </p>
          </div>
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap items-center">
            <div className="max-w-[370px]">
              <Image className="rounded-md object-contain" fill src={hoobank} />
              <div className="w-full flex justify-center gap-x-4 mt-6">
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md hover:scale-110 transition"
                  href="https://hoobank-by-junaid.netlify.app/"
                >
                  Live Demo
                </a>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md hover:scale-110 transition"
                  href="https://github.com/Muhammad-Junaid-24/bank-app-frontend"
                >
                  Github Repo
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
